version: '3'
services:
  db:
    image: postgres:9.6
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 9000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "9000:9000"
    depends_on:
      - comments
  posts:
    image: elixir:1.5.1
    build: ./services/posts
    command: mix phx.server
    volumes:
      - ./services/posts:/posts
    ports:
      - "4000:4000"
    depends_on:
      - db
  comments:
    image: clojure:lein-2.8.1
    build: ./services/comments
    stdin_open: true
    tty: true
    command: lein run
    volumes:
      - ./services/comments:/usr/src/app
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      CLOJURE_ENV: 'development'
