version: '3'
services:
  db:
    image: postgres:9.6
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 9000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "9000:9000"
    depends_on:
      - db
