version: '3'
services:
  db:
    image: postgres:9.6
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 9000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "9000:9000"
  posts:
    image: elixir:1.5.1
    build: ./services/posts
    command: mix phx.server
    volumes:
      - ./services/posts:/posts
    ports:
      - "4000:4000"
    depends_on:
      - db
